name: CI/CD

env:
  GO_VERSION: 1.21.x
  DOCKER_REPO: ghcr.io/korchasa/jira-issues-exporter
  DOCKER_VERSION: latest

on:
  push:
    branches:
      - main
    tags:
      - "v*.*.*"
  pull_request:
    branches: [ main ]

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      -
        uses: actions/checkout@v4
      -
        uses: docker/metadata-action@v5
        id: meta
        with:
          images: |
            ${{ env.DOCKER_REPO }}
          tags: |
            type=ref,event=branch
            type=ref,event=pr
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
      -
        uses: docker/setup-buildx-action@v3
      -
        uses: docker/login-action@v3
#        if: github.event_name != 'pull_request'
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      -
        uses: docker/build-push-action@v5
        with:
#          push: ${{ github.event_name != 'pull_request' }}
          push: true
          platforms: linux/amd64,linux/arm64
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
